name: Use Composite Action

on:
  push:
    branches:
      - main

jobs:
  run-composite-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Use My Composite Action
        uses: ./my-composite-action
        with:
          directory: './example-dir'
          filename: 'example.txt'
