name: CI/CD Pipeline

on:
  push:
    branches:
      - main    # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main    # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The operating system to run on

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install  # Install your project dependencies (example for a Node.js project)

      - name: Run tests
        run: npm test  # Run tests (you can modify it according to your project)

  deploy:
    runs-on: ubuntu-latest  # The operating system for deployment

    needs: build  # This job runs only after the 'build' job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Deploying application"
          # Add your deployment commands here (e.g., using AWS CLI, FTP, etc.)
          # For example, deploy to AWS:
          # aws s3 sync ./dist s3://my-bucket-name
