name: CI/CD Pipeline

on:
  push:
    branches:
      - test    
  pull_request:
    branches:
      - test    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm test || true  # This prevents failure but allows you to see errors
  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Deploying application"
